process.env.APP_KEY = 'secret'
process.env.MONGODB_HOST='localhost'
process.env.MONGODB_PORT = '27017'
process.env.MONGODB_NAME='personal'
process.env.MONGODB_USER='personal'
process.env.MONGODB_PWD='personal'
