## Start training
##! Deve ser logado com usuadio student
mutation {
  startTraining(
    id: "66e7aab2fd1fa9734826181a"
  )
  {
    id
    training_id,
    name,
    description,
    student_id,
    personal_id,
    started_at,
    finished_at,
    exercises {
      id,
      name,
      instructions,
      video,
      rest,
      load,
      load_progress,
      series
  	}
    
  }
}