## Listar os alunos
{
  users(personal_id: "66930805698bbdc15b94a8f1") {
    id
    name
    email
    personal_id
    blocked
    type
  }
}

## Cadastrar novo aluno
mutation {
  createStudent(user: {
    name: "Felipe Student",
    password: "123456k",
    email: "feliperomao08@gmail.com",
    personal_id: "66930805698bbdc15b94a8f1",
  }) {
    id
    name
    email
    personal_id
    blocked
    type
  }
}

## Atualizar aluno
mutation {
  updateStudents(user: {
    id: "669d8b9f44c31eb3f0a0498e",
    name: "Felipe Romao Aluno",
    password: "123456k",
    email: "feliperomao08@gmail.com",
    personal_id: "66930805698bbdc15b94a8f1",
  })
  {
    id
    name
    email
    personal_id
    blocked
    type
  }
}

## Excluir alunos
mutation {
  deleteStudents(ids: ["669b4288d424e0491f039166","669b37ca2d1c8f793226293c","6695612cf9157a4e5e0272f5"])
}